import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://ndoteayinrpxqvwfsftc.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kb3RlYXlpbnJweHF2d2ZzZnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyMzY4OTUsImV4cCI6MjA5NDgxMjg5NX0.KR9wB5SAd7NL_74gz8ZhFO-b_1qL1ZQD3nZH206Y7-c';
const webhookUrl = 'https://script.google.com/macros/s/AKfycbxA79KOZrS3whYS42m3aVdspz66T1tkWmJ0AoLvrGSRspZZxDF3LPPzX1IyFGuGBJRe6g/exec';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function runFullPipelineTest() {
  console.log('--- E-BRAVE PIPELINE VALIDATION TEST ---\n');

  // 1. Mock Student Info (Simulating AssessmentInfo.jsx mapping)
  const studentInfo = {
    fullName: 'Jane Doe Validation',
    grade: 'Grade 12',
    mobile: '+91 9876543210',
    schoolName: 'E-Brave Testing Academy',
    schoolCode: 'EBRAVE-TEST-123'
  };

  const assessmentId = 'test-uuid-' + Date.now();
  console.log('1. Student Data Mapped Correctly:');
  console.log(studentInfo);
  console.log();

  // 2. Generate PDF Blob
  console.log('2. Generating PDF Blob (Simulated)...');
  const dummyPdfContent = 'This is a test PDF generated by the E-Brave AI Pipeline Validation sequence.';
  const pdfBlob = new Blob([dummyPdfContent], { type: 'application/pdf' });
  const fileName = `${Date.now()}_${studentInfo.mobile.replace(/[^0-9]/g, '')}_dossier.pdf`;
  console.log(`   Filename: ${fileName}`);
  console.log('   Status: SUCCESS\n');

  // 3. Upload to Supabase
  console.log('3. Uploading to Supabase [dossiers] bucket...');
  const { data: uploadData, error: uploadError } = await supabase.storage
    .from('dossiers')
    .upload(fileName, pdfBlob, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (uploadError) {
    console.error('   ❌ SUPABASE UPLOAD FAILED:');
    console.error(uploadError);
    return;
  }
  console.log('   ✅ SUPABASE UPLOAD SUCCESSFUL!');
  console.log('   Response Data:', uploadData);
  console.log();

  // 4. Retrieve Public URL
  console.log('4. Retrieving Public URL...');
  const { data: urlData } = supabase.storage.from('dossiers').getPublicUrl(fileName);
  const finalPdfUrl = urlData.publicUrl;
  console.log(`   ✅ PUBLIC URL: ${finalPdfUrl}`);
  console.log();

  // 5. Construct Payload
  console.log('5. Constructing Google Sheets Payload...');
  const payload = {
    assessmentId,
    studentName: studentInfo.fullName,
    className: studentInfo.grade,
    phone: studentInfo.mobile,
    schoolName: studentInfo.schoolName,
    schoolCode: studentInfo.schoolCode,
    archetype: 'The Validation Engineer',
    topCareerMatch: 'Systems Architect',
    primaryRiskFlag: 'None - Perfect Validation',
    pdfUrl: finalPdfUrl,
    assignedCounselor: 'Unassigned',
    sessionStatus: 'Pending'
  };
  console.log('   Exact Payload to be sent:');
  console.log(JSON.stringify(payload, null, 2));
  console.log();

  // 6. Send to Webhook
  console.log('6. Transmitting to Google Apps Script Webhook...');
  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    
    // fetch with redirect will be handled automatically, try to get JSON or text
    const responseText = await response.text();
    console.log('   ✅ WEBHOOK SUBMISSION SUCCESSFUL!');
    console.log('   Webhook Response Body:');
    console.log(`   ${responseText}`);
  } catch (err) {
    console.error('   ❌ WEBHOOK FAILED:');
    console.error(err);
  }

  console.log('\n--- END OF PIPELINE TEST ---');
}

runFullPipelineTest();
